12_10_09_MATTER.pyr	1	1	15	All living things man made or from mother nature itself are made out of matter
12_10_09_MATTER.pyr	1	2	17	Also because matter takes up space and certain amount of material it can be detected and measured
12_10_09_MATTER.pyr	1	3	18	Volume is what matter takes up as space mass is what certain amount of material the object has
12_10_09_MATTER.pyr	1	4	18	Because a cork is hard it will break when you break it and clay will flatten when bended
12_10_09_MATTER.pyr	1	5	16	But when you drop both in water the cork will float and the clay will sink
12_10_09_MATTER.pyr	1	6	7	These characteristics determine the properties of matter
12_10_09_MATTER.pyr	1	7	13	Physical properties are what the object looks like without changing anything about it
12_10_09_MATTER.pyr	1	8	14	Chemical properties describe matter when it is changed with a different kind of property
12_10_09_MATTER.pyr	1	9	6	Energy is the property of matter
12_10_09_MATTER.pyr	1	10	25	Energy can be transferred to one object to another energy cannot be created or destroyed this rule is called the law of conservation of energy
12_10_09_MATTER.pyr	1	11	13	When an object has a motion or position it is called mechanical energy
12_10_09_MATTER.pyr	1	12	13	The energy an object has when it is moving is called kinetic energy
12_10_09_MATTER.pyr	1	13	17	The energy an object has when it has a position or shape is called a potential energy
