12_10_09_MATTER.pyr	1	1	15	All living things man made or from mother nature itself are made out of matter
12_10_09_MATTER.pyr	1	2	17	Also because matter takes up space and certain amount of material it can be detected and measured
12_10_09_MATTER.pyr	1	3	18	Volume is what matter takes up as space mass is what certain amount of material the object has
12_10_09_MATTER.pyr	1	4	18	Because a cork is hard it will break when you break it and clay will flatten when bended
12_10_09_MATTER.pyr	1	5	16	But when you drop both in water the cork will float and the clay will sink
12_10_09_MATTER.pyr	1	6	7	These characteristics determine the properties of matter
12_10_09_MATTER.pyr	1	7	13	Physical properties are what the object looks like without changing anything about it
12_10_09_MATTER.pyr	1	8	14	Chemical properties describe matter when it is changed with a different kind of property
12_10_09_MATTER.pyr	1	9	6	Energy is the property of matter
12_10_09_MATTER.pyr	1	10	25	Energy can be transferred to one object to another energy cannot be created or destroyed this rule is called the law of conservation of energy
12_10_09_MATTER.pyr	1	11	13	When an object has a motion or position it is called mechanical energy
12_10_09_MATTER.pyr	1	12	13	The energy an object has when it is moving is called kinetic energy
12_10_09_MATTER.pyr	1	13	17	The energy an object has when it has a position or shape is called a potential energy
12_10_09_MATTER.pyr	2	1	11	Matter is 'stuff that all substances in the universe is made
12_10_09_MATTER.pyr	2	2	3	It 's everywhere
12_10_09_MATTER.pyr	2	3	46	Since matter takes up space and takes up a certain amount of it all matter can be detected and measured the way you classify these is by their physical properties things like is it a solid liquid or gas how much it weighs basically the makeup
12_10_09_MATTER.pyr	2	4	13	Energy is closely related to matter because it 's a property of matter
12_10_09_MATTER.pyr	2	5	15	The law of energy is that it cannot be created nor destroyed it simply transferred
12_10_09_MATTER.pyr	2	6	8	Matter can undergo either physical or chemical change
12_10_09_MATTER.pyr	2	7	21	A physical change is changing like size and shape without changing the chemical properties but a chemical is exactly their changing
12_10_09_MATTER.pyr	2	8	19	The chemical properties like burning paper mechanical energy is energy by an object created by its position or motion
12_10_09_MATTER.pyr	3	1	7	Matter is what makes up our earth
12_10_09_MATTER.pyr	3	2	11	It contain volume as well as mass which makes it measurable
12_10_09_MATTER.pyr	3	3	7	You senses is what helps classify matter
12_10_09_MATTER.pyr	3	4	10	The two types of physical properties is size and shape
12_10_09_MATTER.pyr	3	5	14	Chemical changes don not change in size and shape but change into new substances
12_10_09_MATTER.pyr	3	6	8	One very important property of matter is energy
12_10_09_MATTER.pyr	3	7	14	To make matter function or work properly you need energy to make it happen
12_10_09_MATTER.pyr	3	8	10	Energy is one very important substance as well as strong
12_10_09_MATTER.pyr	3	9	13	Energy is used to create all kinds of substances which makes non destroyable
12_10_09_MATTER.pyr	3	10	23	Mechanical energy on the other hand is energy an object has because motion which is kinetic energy and position which is potential energy
12_10_09_MATTER.pyr	4	1	5	What are we made of
12_10_09_MATTER.pyr	4	2	11	Matter is what characteristics us humans all all of our surroundings
12_10_09_MATTER.pyr	4	3	7	Matter describes what objects out made of
12_10_09_MATTER.pyr	4	4	13	Matter is composed by volume and mass which can be detected and measured
12_10_09_MATTER.pyr	4	5	20	All matter has a physical and chemical property which defines its shape and the reactions it has towards dramatic change
12_10_09_MATTER.pyr	4	6	28	Although physical and chemical properties are part of matter physical properties are the ones that can be observed while chemical properties determines the behavior to illegible word conditions
12_10_09_MATTER.pyr	4	7	11	Matter is also made out of energy kinetic or potential energy
12_10_09_MATTER.pyr	4	8	13	One is described by its speed and the other by volume or shape
12_10_09_MATTER.pyr	4	9	17	All of the above defines matter the stuff that all objects in the universe are made of
12_10_09_MATTER.pyr	5	1	11	Matter are what all objects and substances are made up of
12_10_09_MATTER.pyr	5	2	7	All matter has energy volume and mass
12_10_09_MATTER.pyr	5	3	30	In order to classify matter we have have physical and chemical properties are the density ductility malleability boilling point melting point electrical conductivity solubility and I am sure much more
12_10_09_MATTER.pyr	5	4	19	Energy can be transferred from one object or system to another but energy can not be created nor destroyed
12_10_09_MATTER.pyr	5	5	19	Mechanical energy are kinetic energy and potential energy kinetic energy deals with the energy with object while its moving
12_10_09_MATTER.pyr	5	6	14	Potential energy is the energy and object has because of its position or shape
12_10_09_MATTER.pyr	6	1	12	Matter is the 'stuff that all objects and substances are made of
12_10_09_MATTER.pyr	6	2	12	All matter has volume and mass and can be found and measured
12_10_09_MATTER.pyr	6	3	10	You can see smell and feel some types of matter
12_10_09_MATTER.pyr	6	4	8	For example trees rock bicycles air smoke etc.
12_10_09_MATTER.pyr	6	5	12	Characteristics changing in the objects help classify matter that is called properties
12_10_09_MATTER.pyr	6	6	9	There is two types of properties physical and chemical
12_10_09_MATTER.pyr	6	7	16	The difference between the two is the change in the objects properties chemical and appearance physical
12_10_09_MATTER.pyr	6	8	12	Energy is also a property of matter and all matter has it
12_10_09_MATTER.pyr	6	9	25	The rule known as the law of conservation states that energy can be transferred to one object to another and cannot be created nor destroyed
12_10_09_MATTER.pyr	6	10	13	Mechanical energy is energy an object has due to its position or motion
12_10_09_MATTER.pyr	6	11	7	There 's two types of mechanical energy
12_10_09_MATTER.pyr	6	12	12	Kinetic energy is one and has energy because of an objects motion
12_10_09_MATTER.pyr	6	13	15	Potential energy is the second and has energy because of an objects position or shape
12_10_09_MATTER.pyr	7	1	10	Matter is the stuff that everything is made up of
12_10_09_MATTER.pyr	7	2	6	All matter has mass and volume
12_10_09_MATTER.pyr	7	3	30	It has physical properties which can be changed by the appearance only and has chemical properties which a substance can be changed into something different that can not be undone
12_10_09_MATTER.pyr	7	4	8	Energy can be transferred but never be destroyed
12_10_09_MATTER.pyr	7	5	9	There are two type of energy kinetic and potential
12_10_09_MATTER.pyr	7	6	10	Kinetic is energy that an object has as it moves
12_10_09_MATTER.pyr	7	7	13	Potential energy is the energy it has do to its position or shape
12_10_09_MATTER.pyr	8	1	19	In this passage I learned about matter properties of matter physical and chemical changes energy and forms of energy
12_10_09_MATTER.pyr	8	2	18	I learned that matter is the 'stuff that all objects and substances in the universe are made of
12_10_09_MATTER.pyr	8	3	12	And because matter takes up space it can be detected and measure
12_10_09_MATTER.pyr	8	4	8	Matter can be easily observed with our senses
12_10_09_MATTER.pyr	8	5	11	I also learned that matter has both physical and chemical properties
12_10_09_MATTER.pyr	8	6	12	Physical properties are those that can be observed without changing its identity
12_10_09_MATTER.pyr	8	7	19	Unlike chemical properties its based on its ability to change into a new kind of matter with different properties
12_10_09_MATTER.pyr	8	8	27	A physical change is a change in its shape or size and a chemical change is when your able to produce a new material with new properties
12_10_09_MATTER.pyr	8	9	11	Energy is a property of matter and all matter has it
12_10_09_MATTER.pyr	8	10	19	Energy comes in different forms mechanical energy is the energy an object has because of its motion or position
12_10_09_MATTER.pyr	8	11	10	There are two kinds of energy kinetic and potential energy
12_10_09_MATTER.pyr	8	12	22	Kinetic energy is when an object is moving and potential energy is energy an object has because of its position or shape
12_10_09_MATTER.pyr	9	1	18	Matter is every where the clothes I wear the food I eat the air I breathe all matter
12_10_09_MATTER.pyr	9	2	11	You are in contact with matter every nanosecond of your life
12_10_09_MATTER.pyr	9	3	14	When you chop vegetables for a soup you put physical cough on the vegetables
12_10_09_MATTER.pyr	9	4	20	After you eat those vegetables they are broken down chemically in your body to absorb all the vitamins and minerals
12_10_09_MATTER.pyr	9	5	30	In those vitamins and minerals is energy that fuels your body and keeps you alive but that energy is not destroyed it is released as heat and used somewhere else
12_10_09_MATTER.pyr	9	6	13	I am putting mechanical energy to work right now in writing this paper
12_10_09_MATTER.pyr	10	1	14	Matter is the stuff that all objects in the world are made up of
12_10_09_MATTER.pyr	10	2	11	You can be sure that everything in the world has matter
12_10_09_MATTER.pyr	10	3	18	Even water which as no definite shape or a gas with no definite shape or volume has matter
12_10_09_MATTER.pyr	10	4	16	Without matter the world would literally fall apart matter is detected by both mass and volume
12_10_09_MATTER.pyr	10	5	9	That is how you would know it is matter
12_10_09_MATTER.pyr	11	1	5	Matter is a physical substance
12_10_09_MATTER.pyr	11	2	9	All things in this universe are made of matter
12_10_09_MATTER.pyr	11	3	9	Some types of matter are observed easily by senses
12_10_09_MATTER.pyr	11	4	4	Matter also has properties
12_10_09_MATTER.pyr	11	5	8	Physical properties are those that can be observed
12_10_09_MATTER.pyr	11	6	9	Malleability is also another example of a physical property
12_10_09_MATTER.pyr	11	7	10	Chemical properties change matter into a new kind of matter
12_10_09_MATTER.pyr	11	8	11	Matter also has energy but energy cannot be created or destroyed
12_10_09_MATTER.pyr	12	1	8	Matter is basically what things are made of
12_10_09_MATTER.pyr	12	2	14	All of the matter is the universe can be detected because of its volume
12_10_09_MATTER.pyr	12	3	8	Matter can also be recognized by our senses
12_10_09_MATTER.pyr	12	4	10	Things that help us identify and recognize matter are properties
12_10_09_MATTER.pyr	12	5	6	Matter has a thing call energy
12_10_09_MATTER.pyr	12	6	13	Energy that is made by the motion of an object is called mechanical
12_10_09_MATTER.pyr	13	1	13	Matter is something that takes up space and is perceived by our universe
12_10_09_MATTER.pyr	13	2	7	All matter can be detected and measure
12_10_09_MATTER.pyr	13	3	19	Some can be seen or it can be difficult to seen for example cats houses flowers can be seen
12_10_09_MATTER.pyr	13	4	7	It 's difficult to see dust mites
12_10_09_MATTER.pyr	13	5	15	There are ways matter is classify one is physical property and the other chemical property
12_10_09_MATTER.pyr	13	6	24	Physical property is when the object doesn not change but it may change the way it looks and it 's still the same thing
12_10_09_MATTER.pyr	13	7	15	Chemical property has the ability to change into a completely new matter with other properties
12_10_09_MATTER.pyr	13	8	37	The difference between physical change and chemical change is that physical change the object has changed appearance but the properties keep being the same and in chemical change the original object has changed into a new kind
12_10_09_MATTER.pyr	13	9	11	All matter has energy because it 's a property of matter
12_10_09_MATTER.pyr	13	10	10	Energy cannot be destroyed but it give energy to others
12_10_09_MATTER.pyr	13	11	9	This is called the law of conservation of energy
12_10_09_MATTER.pyr	13	12	16	Whenever an object is moving on if it has a position it 's called mechanical energy
12_10_09_MATTER.pyr	13	13	21	There are types of mechanical energy kinetic is when object is moving and potential is when the object has a position
12_10_09_MATTER.pyr	14	1	11	Matter is what all objects and substances are made up of
12_10_09_MATTER.pyr	14	2	11	It can be measured because all matter has mass and volume
12_10_09_MATTER.pyr	14	3	7	There are different properties and chemical properties
12_10_09_MATTER.pyr	14	4	6	These occur when there are changes
12_10_09_MATTER.pyr	14	5	33	When there is a physical change the object can change into a different form or shape and can change back but a chemical change the object can change but illegible word 17 was
12_10_09_MATTER.pyr	14	6	4	All matter has energy
12_10_09_MATTER.pyr	14	7	13	It has mechanical energy because the object has motion or of its position
12_10_09_MATTER.pyr	14	8	18	The is the law of conservation of energy which states that energy can not be created or destroyed
12_10_09_MATTER.pyr	15	1	14	Matter is the stuff all objects and substances in the universe are made of
12_10_09_MATTER.pyr	15	2	26	All matter can be detected because it take up space which is known as volume and contains certain amount of material which is known as mass
12_10_09_MATTER.pyr	15	3	8	We can classify matter with our five senses
12_10_09_MATTER.pyr	15	4	8	All matter has both physical and chemical properties
12_10_09_MATTER.pyr	15	5	7	Physical properties can change shape and size
12_10_09_MATTER.pyr	15	6	7	Chemical properties change by producing new substances
12_10_09_MATTER.pyr	15	7	4	All matter has energy
12_10_09_MATTER.pyr	15	8	7	Energy can not be created or destroyed
12_10_09_MATTER.pyr	15	9	22	Mechanical energy is the energy an object has because of its motion known as kinetic energy and position known as potential energy
12_10_09_MATTER.pyr	16	1	13	Matter are all objects and substances in the universe that are made of
12_10_09_MATTER.pyr	16	2	18	Because it takes up more space that has volume and also contains certain amount of material has mass
12_10_09_MATTER.pyr	16	3	13	Other things that can help us to identity or classify is the properties
12_10_09_MATTER.pyr	16	4	22	Also the difference between physical and chemical change is that physical because it 's size and shape and chemical produces new substances
12_10_09_MATTER.pyr	16	5	12	Energy is related to matter because it is a property of matter
12_10_09_MATTER.pyr	16	6	26	The law of conservation of energy is when energy can be transferred from one object or system to another and energy cannot be created and destroyed
12_10_09_MATTER.pyr	16	7	15	And the mechanical energy is an object that has because of its motion and position
12_10_09_MATTER.pyr	17	1	9	Matter is the mass and volume of an object
12_10_09_MATTER.pyr	17	2	4	All matter has energy
12_10_09_MATTER.pyr	17	3	18	Matter can be detected no matter what because it takes up volume and contains some kind of mass
12_10_09_MATTER.pyr	17	4	5	Properties help to classify matter
12_10_09_MATTER.pyr	17	5	13	Matter can be detected under all circumstances because of the volume and mass
12_10_09_MATTER.pyr	17	6	4	All matter contains energy
12_10_09_MATTER.pyr	18	1	5	Everything is made of matter
12_10_09_MATTER.pyr	18	2	6	Matter has volume and has mass
12_10_09_MATTER.pyr	18	3	19	Some matter is visible and others are only visible with the use of a device such as the microscope
12_10_09_MATTER.pyr	18	4	5	Matter is classified by properties
12_10_09_MATTER.pyr	18	5	5	Physical properties can be seen
12_10_09_MATTER.pyr	18	6	12	Chemical properties can be changed into a new kind with different properties
12_10_09_MATTER.pyr	18	7	9	Change can occur in both physical and chemical properties
12_10_09_MATTER.pyr	18	8	5	Physical change can be restored
12_10_09_MATTER.pyr	18	9	7	Chemica change creates a new substance property
12_10_09_MATTER.pyr	18	10	6	Energy is another property of matter
12_10_09_MATTER.pyr	18	11	15	The law of conservation of energy states that energy can not be created or destroyed
12_10_09_MATTER.pyr	18	12	11	Kinetic energy and potential energy are two types of mechanical energy
12_10_09_MATTER.pyr	19	1	8	Matter is what every thing is made of
12_10_09_MATTER.pyr	19	2	13	All matter can be detected and measured because it takes up space volume
12_10_09_MATTER.pyr	19	3	8	Matter can be classified by there physical properties
12_10_09_MATTER.pyr	19	4	22	The difference between physical properties and chemical properties is physical changes make it look different but it is still the same thing
12_10_09_MATTER.pyr	19	5	9	Chemical changes the object in to something totally different
12_10_09_MATTER.pyr	19	6	4	All matter has energy
12_10_09_MATTER.pyr	19	7	7	Energy can be neither created nor destroyed
12_10_09_MATTER.pyr	19	8	14	Mechanical energy is the energy an object has because of its shape or position
12_10_09_MATTER.pyr	20	1	6	Matter is something that occupies space
12_10_09_MATTER.pyr	20	2	11	All matter has mass therefore matter can be detected and measured
12_10_09_MATTER.pyr	20	3	7	Properties help to identify and classify matter
12_10_09_MATTER.pyr	20	4	11	One example of a property is energy all matter contains energy
12_10_09_MATTER.pyr	20	5	24	There are many forms of energy it can be transferred from one object or system to another but it cannot be created or destroyed
12_10_09_MATTER.pyr	20	6	8	Another property of matter is physical and chemical
12_10_09_MATTER.pyr	20	7	19	A physical properties are those that can be observed without changing the make up or identity of the matter
12_10_09_MATTER.pyr	20	8	19	Chemical properties describe matter based on its ability to change into a new kind of matter with different properties
12_10_09_MATTER.pyr	20	9	17	So the difference between physical and chemical changes is that physical can be reversible and chemical cannot
12_10_09_MATTER.pyr	20	10	20	One form of energy is mechanical energy which is the energy an object has because of its motion or position
yinghui_12_10_09_MATTER.pyr	1	1	15	All living things man made or from mother nature itself are made out of matter
yinghui_12_10_09_MATTER.pyr	1	2	17	Also because matter takes up space and certain amount of material it can be detected and measured
yinghui_12_10_09_MATTER.pyr	1	3	18	Volume is what matter takes up as space mass is what certain amount of material the object has
yinghui_12_10_09_MATTER.pyr	1	4	18	Because a cork is hard it will break when you break it and clay will flatten when bended
yinghui_12_10_09_MATTER.pyr	1	5	16	But when you drop both in water the cork will float and the clay will sink
yinghui_12_10_09_MATTER.pyr	1	6	7	These characteristics determine the properties of matter
yinghui_12_10_09_MATTER.pyr	1	7	13	Physical properties are what the object looks like without changing anything about it
yinghui_12_10_09_MATTER.pyr	1	8	14	Chemical properties describe matter when it is changed with a different kind of property
yinghui_12_10_09_MATTER.pyr	1	9	6	Energy is the property of matter
yinghui_12_10_09_MATTER.pyr	1	10	25	Energy can be transferred to one object to another energy cannot be created or destroyed this rule is called the law of conservation of energy
yinghui_12_10_09_MATTER.pyr	1	11	13	When an object has a motion or position it is called mechanical energy
yinghui_12_10_09_MATTER.pyr	1	12	13	The energy an object has when it is moving is called kinetic energy
yinghui_12_10_09_MATTER.pyr	1	13	17	The energy an object has when it has a position or shape is called a potential energy
yinghui_12_10_09_MATTER.pyr	2	1	11	Matter is 'stuff that all substances in the universe is made
yinghui_12_10_09_MATTER.pyr	2	2	3	It 's everywhere
yinghui_12_10_09_MATTER.pyr	2	3	46	Since matter takes up space and takes up a certain amount of it all matter can be detected and measured the way you classify these is by their physical properties things like is it a solid liquid or gas how much it weighs basically the makeup
yinghui_12_10_09_MATTER.pyr	2	4	13	Energy is closely related to matter because it 's a property of matter
yinghui_12_10_09_MATTER.pyr	2	5	15	The law of energy is that it cannot be created nor destroyed it simply transferred
yinghui_12_10_09_MATTER.pyr	2	6	8	Matter can undergo either physical or chemical change
yinghui_12_10_09_MATTER.pyr	2	7	21	A physical change is changing like size and shape without changing the chemical properties but a chemical is exactly their changing
yinghui_12_10_09_MATTER.pyr	2	8	19	The chemical properties like burning paper mechanical energy is energy by an object created by its position or motion
yinghui_12_10_09_MATTER.pyr	3	1	7	Matter is what makes up our earth
yinghui_12_10_09_MATTER.pyr	3	2	11	It contain volume as well as mass which makes it measurable
yinghui_12_10_09_MATTER.pyr	3	3	7	You senses is what helps classify matter
yinghui_12_10_09_MATTER.pyr	3	4	10	The two types of physical properties is size and shape
yinghui_12_10_09_MATTER.pyr	3	5	14	Chemical changes don not change in size and shape but change into new substances
yinghui_12_10_09_MATTER.pyr	3	6	8	One very important property of matter is energy
yinghui_12_10_09_MATTER.pyr	3	7	14	To make matter function or work properly you need energy to make it happen
yinghui_12_10_09_MATTER.pyr	3	8	10	Energy is one very important substance as well as strong
yinghui_12_10_09_MATTER.pyr	3	9	13	Energy is used to create all kinds of substances which makes non destroyable
yinghui_12_10_09_MATTER.pyr	3	10	23	Mechanical energy on the other hand is energy an object has because motion which is kinetic energy and position which is potential energy
yinghui_12_10_09_MATTER.pyr	4	1	5	What are we made of
yinghui_12_10_09_MATTER.pyr	4	2	11	Matter is what characteristics us humans all all of our surroundings
yinghui_12_10_09_MATTER.pyr	4	3	7	Matter describes what objects out made of
yinghui_12_10_09_MATTER.pyr	4	4	13	Matter is composed by volume and mass which can be detected and measured
yinghui_12_10_09_MATTER.pyr	4	5	20	All matter has a physical and chemical property which defines its shape and the reactions it has towards dramatic change
yinghui_12_10_09_MATTER.pyr	4	6	28	Although physical and chemical properties are part of matter physical properties are the ones that can be observed while chemical properties determines the behavior to illegible word conditions
yinghui_12_10_09_MATTER.pyr	4	7	11	Matter is also made out of energy kinetic or potential energy
yinghui_12_10_09_MATTER.pyr	4	8	13	One is described by its speed and the other by volume or shape
yinghui_12_10_09_MATTER.pyr	4	9	17	All of the above defines matter the stuff that all objects in the universe are made of
yinghui_12_10_09_MATTER.pyr	5	1	11	Matter are what all objects and substances are made up of
yinghui_12_10_09_MATTER.pyr	5	2	7	All matter has energy volume and mass
yinghui_12_10_09_MATTER.pyr	5	3	30	In order to classify matter we have have physical and chemical properties are the density ductility malleability boilling point melting point electrical conductivity solubility and I am sure much more
yinghui_12_10_09_MATTER.pyr	5	4	19	Energy can be transferred from one object or system to another but energy can not be created nor destroyed
yinghui_12_10_09_MATTER.pyr	5	5	19	Mechanical energy are kinetic energy and potential energy kinetic energy deals with the energy with object while its moving
yinghui_12_10_09_MATTER.pyr	5	6	14	Potential energy is the energy and object has because of its position or shape
yinghui_12_10_09_MATTER.pyr	6	1	12	Matter is the 'stuff that all objects and substances are made of
yinghui_12_10_09_MATTER.pyr	6	2	12	All matter has volume and mass and can be found and measured
yinghui_12_10_09_MATTER.pyr	6	3	10	You can see smell and feel some types of matter
yinghui_12_10_09_MATTER.pyr	6	4	8	For example trees rock bicycles air smoke etc.
yinghui_12_10_09_MATTER.pyr	6	5	12	Characteristics changing in the objects help classify matter that is called properties
yinghui_12_10_09_MATTER.pyr	6	6	9	There is two types of properties physical and chemical
yinghui_12_10_09_MATTER.pyr	6	7	16	The difference between the two is the change in the objects properties chemical and appearance physical
yinghui_12_10_09_MATTER.pyr	6	8	12	Energy is also a property of matter and all matter has it
yinghui_12_10_09_MATTER.pyr	6	9	25	The rule known as the law of conservation states that energy can be transferred to one object to another and cannot be created nor destroyed
yinghui_12_10_09_MATTER.pyr	6	10	13	Mechanical energy is energy an object has due to its position or motion
yinghui_12_10_09_MATTER.pyr	6	11	7	There 's two types of mechanical energy
yinghui_12_10_09_MATTER.pyr	6	12	12	Kinetic energy is one and has energy because of an objects motion
yinghui_12_10_09_MATTER.pyr	6	13	15	Potential energy is the second and has energy because of an objects position or shape
yinghui_12_10_09_MATTER.pyr	7	1	10	Matter is the stuff that everything is made up of
yinghui_12_10_09_MATTER.pyr	7	2	6	All matter has mass and volume
yinghui_12_10_09_MATTER.pyr	7	3	30	It has physical properties which can be changed by the appearance only and has chemical properties which a substance can be changed into something different that can not be undone
yinghui_12_10_09_MATTER.pyr	7	4	8	Energy can be transferred but never be destroyed
yinghui_12_10_09_MATTER.pyr	7	5	9	There are two type of energy kinetic and potential
yinghui_12_10_09_MATTER.pyr	7	6	10	Kinetic is energy that an object has as it moves
yinghui_12_10_09_MATTER.pyr	7	7	13	Potential energy is the energy it has do to its position or shape
yinghui_12_10_09_MATTER.pyr	8	1	19	In this passage I learned about matter properties of matter physical and chemical changes energy and forms of energy
yinghui_12_10_09_MATTER.pyr	8	2	18	I learned that matter is the 'stuff that all objects and substances in the universe are made of
yinghui_12_10_09_MATTER.pyr	8	3	12	And because matter takes up space it can be detected and measure
yinghui_12_10_09_MATTER.pyr	8	4	8	Matter can be easily observed with our senses
yinghui_12_10_09_MATTER.pyr	8	5	11	I also learned that matter has both physical and chemical properties
yinghui_12_10_09_MATTER.pyr	8	6	12	Physical properties are those that can be observed without changing its identity
yinghui_12_10_09_MATTER.pyr	8	7	19	Unlike chemical properties its based on its ability to change into a new kind of matter with different properties
yinghui_12_10_09_MATTER.pyr	8	8	27	A physical change is a change in its shape or size and a chemical change is when your able to produce a new material with new properties
yinghui_12_10_09_MATTER.pyr	8	9	11	Energy is a property of matter and all matter has it
yinghui_12_10_09_MATTER.pyr	8	10	19	Energy comes in different forms mechanical energy is the energy an object has because of its motion or position
yinghui_12_10_09_MATTER.pyr	8	11	10	There are two kinds of energy kinetic and potential energy
yinghui_12_10_09_MATTER.pyr	8	12	22	Kinetic energy is when an object is moving and potential energy is energy an object has because of its position or shape
yinghui_12_10_09_MATTER.pyr	9	1	18	Matter is every where the clothes I wear the food I eat the air I breathe all matter
yinghui_12_10_09_MATTER.pyr	9	2	11	You are in contact with matter every nanosecond of your life
yinghui_12_10_09_MATTER.pyr	9	3	14	When you chop vegetables for a soup you put physical cough on the vegetables
yinghui_12_10_09_MATTER.pyr	9	4	20	After you eat those vegetables they are broken down chemically in your body to absorb all the vitamins and minerals
yinghui_12_10_09_MATTER.pyr	9	5	30	In those vitamins and minerals is energy that fuels your body and keeps you alive but that energy is not destroyed it is released as heat and used somewhere else
yinghui_12_10_09_MATTER.pyr	9	6	13	I am putting mechanical energy to work right now in writing this paper
yinghui_12_10_09_MATTER.pyr	10	1	14	Matter is the stuff that all objects in the world are made up of
yinghui_12_10_09_MATTER.pyr	10	2	11	You can be sure that everything in the world has matter
yinghui_12_10_09_MATTER.pyr	10	3	18	Even water which as no definite shape or a gas with no definite shape or volume has matter
yinghui_12_10_09_MATTER.pyr	10	4	16	Without matter the world would literally fall apart matter is detected by both mass and volume
yinghui_12_10_09_MATTER.pyr	10	5	9	That is how you would know it is matter
yinghui_12_10_09_MATTER.pyr	11	1	5	Matter is a physical substance
yinghui_12_10_09_MATTER.pyr	11	2	9	All things in this universe are made of matter
yinghui_12_10_09_MATTER.pyr	11	3	9	Some types of matter are observed easily by senses
yinghui_12_10_09_MATTER.pyr	11	4	4	Matter also has properties
yinghui_12_10_09_MATTER.pyr	11	5	8	Physical properties are those that can be observed
yinghui_12_10_09_MATTER.pyr	11	6	9	Malleability is also another example of a physical property
yinghui_12_10_09_MATTER.pyr	11	7	10	Chemical properties change matter into a new kind of matter
yinghui_12_10_09_MATTER.pyr	11	8	11	Matter also has energy but energy cannot be created or destroyed
yinghui_12_10_09_MATTER.pyr	12	1	8	Matter is basically what things are made of
yinghui_12_10_09_MATTER.pyr	12	2	14	All of the matter is the universe can be detected because of its volume
yinghui_12_10_09_MATTER.pyr	12	3	8	Matter can also be recognized by our senses
yinghui_12_10_09_MATTER.pyr	12	4	10	Things that help us identify and recognize matter are properties
yinghui_12_10_09_MATTER.pyr	12	5	6	Matter has a thing call energy
yinghui_12_10_09_MATTER.pyr	12	6	13	Energy that is made by the motion of an object is called mechanical
yinghui_12_10_09_MATTER.pyr	13	1	13	Matter is something that takes up space and is perceived by our universe
yinghui_12_10_09_MATTER.pyr	13	2	7	All matter can be detected and measure
yinghui_12_10_09_MATTER.pyr	13	3	19	Some can be seen or it can be difficult to seen for example cats houses flowers can be seen
yinghui_12_10_09_MATTER.pyr	13	4	7	It 's difficult to see dust mites
yinghui_12_10_09_MATTER.pyr	13	5	15	There are ways matter is classify one is physical property and the other chemical property
yinghui_12_10_09_MATTER.pyr	13	6	24	Physical property is when the object doesn not change but it may change the way it looks and it 's still the same thing
yinghui_12_10_09_MATTER.pyr	13	7	15	Chemical property has the ability to change into a completely new matter with other properties
yinghui_12_10_09_MATTER.pyr	13	8	37	The difference between physical change and chemical change is that physical change the object has changed appearance but the properties keep being the same and in chemical change the original object has changed into a new kind
yinghui_12_10_09_MATTER.pyr	13	9	11	All matter has energy because it 's a property of matter
yinghui_12_10_09_MATTER.pyr	13	10	10	Energy cannot be destroyed but it give energy to others
yinghui_12_10_09_MATTER.pyr	13	11	9	This is called the law of conservation of energy
yinghui_12_10_09_MATTER.pyr	13	12	16	Whenever an object is moving on if it has a position it 's called mechanical energy
yinghui_12_10_09_MATTER.pyr	13	13	21	There are types of mechanical energy kinetic is when object is moving and potential is when the object has a position
yinghui_12_10_09_MATTER.pyr	14	1	11	Matter is what all objects and substances are made up of
yinghui_12_10_09_MATTER.pyr	14	2	11	It can be measured because all matter has mass and volume
yinghui_12_10_09_MATTER.pyr	14	3	7	There are different properties and chemical properties
yinghui_12_10_09_MATTER.pyr	14	4	6	These occur when there are changes
yinghui_12_10_09_MATTER.pyr	14	5	33	When there is a physical change the object can change into a different form or shape and can change back but a chemical change the object can change but illegible word 17 was
yinghui_12_10_09_MATTER.pyr	14	6	4	All matter has energy
yinghui_12_10_09_MATTER.pyr	14	7	13	It has mechanical energy because the object has motion or of its position
yinghui_12_10_09_MATTER.pyr	14	8	18	The is the law of conservation of energy which states that energy can not be created or destroyed
yinghui_12_10_09_MATTER.pyr	15	1	14	Matter is the stuff all objects and substances in the universe are made of
yinghui_12_10_09_MATTER.pyr	15	2	26	All matter can be detected because it take up space which is known as volume and contains certain amount of material which is known as mass
yinghui_12_10_09_MATTER.pyr	15	3	8	We can classify matter with our five senses
yinghui_12_10_09_MATTER.pyr	15	4	8	All matter has both physical and chemical properties
yinghui_12_10_09_MATTER.pyr	15	5	7	Physical properties can change shape and size
yinghui_12_10_09_MATTER.pyr	15	6	7	Chemical properties change by producing new substances
yinghui_12_10_09_MATTER.pyr	15	7	4	All matter has energy
yinghui_12_10_09_MATTER.pyr	15	8	7	Energy can not be created or destroyed
yinghui_12_10_09_MATTER.pyr	15	9	22	Mechanical energy is the energy an object has because of its motion known as kinetic energy and position known as potential energy
yinghui_12_10_09_MATTER.pyr	16	1	13	Matter are all objects and substances in the universe that are made of
yinghui_12_10_09_MATTER.pyr	16	2	18	Because it takes up more space that has volume and also contains certain amount of material has mass
yinghui_12_10_09_MATTER.pyr	16	3	13	Other things that can help us to identity or classify is the properties
yinghui_12_10_09_MATTER.pyr	16	4	22	Also the difference between physical and chemical change is that physical because it 's size and shape and chemical produces new substances
yinghui_12_10_09_MATTER.pyr	16	5	12	Energy is related to matter because it is a property of matter
yinghui_12_10_09_MATTER.pyr	16	6	26	The law of conservation of energy is when energy can be transferred from one object or system to another and energy cannot be created and destroyed
yinghui_12_10_09_MATTER.pyr	16	7	15	And the mechanical energy is an object that has because of its motion and position
yinghui_12_10_09_MATTER.pyr	17	1	9	Matter is the mass and volume of an object
yinghui_12_10_09_MATTER.pyr	17	2	4	All matter has energy
yinghui_12_10_09_MATTER.pyr	17	3	18	Matter can be detected no matter what because it takes up volume and contains some kind of mass
yinghui_12_10_09_MATTER.pyr	17	4	5	Properties help to classify matter
yinghui_12_10_09_MATTER.pyr	17	5	13	Matter can be detected under all circumstances because of the volume and mass
yinghui_12_10_09_MATTER.pyr	17	6	4	All matter contains energy
yinghui_12_10_09_MATTER.pyr	18	1	5	Everything is made of matter
yinghui_12_10_09_MATTER.pyr	18	2	6	Matter has volume and has mass
yinghui_12_10_09_MATTER.pyr	18	3	19	Some matter is visible and others are only visible with the use of a device such as the microscope
yinghui_12_10_09_MATTER.pyr	18	4	5	Matter is classified by properties
yinghui_12_10_09_MATTER.pyr	18	5	5	Physical properties can be seen
yinghui_12_10_09_MATTER.pyr	18	6	12	Chemical properties can be changed into a new kind with different properties
yinghui_12_10_09_MATTER.pyr	18	7	9	Change can occur in both physical and chemical properties
yinghui_12_10_09_MATTER.pyr	18	8	5	Physical change can be restored
yinghui_12_10_09_MATTER.pyr	18	9	7	Chemica change creates a new substance property
yinghui_12_10_09_MATTER.pyr	18	10	6	Energy is another property of matter
yinghui_12_10_09_MATTER.pyr	18	11	15	The law of conservation of energy states that energy can not be created or destroyed
yinghui_12_10_09_MATTER.pyr	18	12	11	Kinetic energy and potential energy are two types of mechanical energy
yinghui_12_10_09_MATTER.pyr	19	1	8	Matter is what every thing is made of
yinghui_12_10_09_MATTER.pyr	19	2	13	All matter can be detected and measured because it takes up space volume
yinghui_12_10_09_MATTER.pyr	19	3	8	Matter can be classified by there physical properties
yinghui_12_10_09_MATTER.pyr	19	4	22	The difference between physical properties and chemical properties is physical changes make it look different but it is still the same thing
yinghui_12_10_09_MATTER.pyr	19	5	9	Chemical changes the object in to something totally different
yinghui_12_10_09_MATTER.pyr	19	6	4	All matter has energy
yinghui_12_10_09_MATTER.pyr	19	7	7	Energy can be neither created nor destroyed
yinghui_12_10_09_MATTER.pyr	19	8	14	Mechanical energy is the energy an object has because of its shape or position
yinghui_12_10_09_MATTER.pyr	20	1	6	Matter is something that occupies space
yinghui_12_10_09_MATTER.pyr	20	2	11	All matter has mass therefore matter can be detected and measured
yinghui_12_10_09_MATTER.pyr	20	3	7	Properties help to identify and classify matter
yinghui_12_10_09_MATTER.pyr	20	4	11	One example of a property is energy all matter contains energy
yinghui_12_10_09_MATTER.pyr	20	5	24	There are many forms of energy it can be transferred from one object or system to another but it cannot be created or destroyed
yinghui_12_10_09_MATTER.pyr	20	6	8	Another property of matter is physical and chemical
yinghui_12_10_09_MATTER.pyr	20	7	19	A physical properties are those that can be observed without changing the make up or identity of the matter
yinghui_12_10_09_MATTER.pyr	20	8	19	Chemical properties describe matter based on its ability to change into a new kind of matter with different properties
yinghui_12_10_09_MATTER.pyr	20	9	17	So the difference between physical and chemical changes is that physical can be reversible and chemical cannot
yinghui_12_10_09_MATTER.pyr	20	10	20	One form of energy is mechanical energy which is the energy an object has because of its motion or position
